[author]
   name = "Alecs"
   image = "/assets/images/profile.png"
   headline = "Reverse engineering stuff and hacking things"
   bio = "Sr. DevOPS/Sysadmin. Mostly coding, networking and mixes of the two. Father, animal lover, vinyl addict, amateur photographer."