colorScheme = "slate"
disableImageOptimization = true
defaultBackgroundImage = "background-cover.gif"
defaultAppearance = "dark"
autoSwitchAppearance = false

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "background-cover.gif" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = false
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[header]
  layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[article]
  showHero = true
  heroStyle = "background" 
  showSummary = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showCards = true
  groupByYear = false
  cardView = true
  showHero = true
  heroStyle = "background" 