colorScheme = "neon"
disableImageOptimization = false
defaultBackgroundImage = "/index_style/images/background-cover.gif"

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/index_style/images/background-cover.gif" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[header]
  layout = "fixed"

[article]
  showHero = true
  heroStyle = "background" 
  showSummary = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showCards = true
  groupByYear = false
  cardView = true